defaults:
  - config
  - _self_

allocation_mode: sglang:d1p1t1

gconfig:
  n_samples: 1
  agent:
    adv_estimator: gigpo

rollout:
  max_concurrent_rollouts: 24
  consumer_batch_size: 16

valid_dataset:
  batch_size: 16

external_engine:
  max_concurrent_rollouts: 16
  consumer_batch_size: 8
